spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=1234
# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
# Spring Boot
spring.application.name=web-security-app
server.port=8080
